services:
  devcontainer:
    image: node:24
    init: true
    user: node
    working_dir: /workspace
    command: sleep infinity

    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules # best practice (behavior consistency & performance)

    ports:
      - "${PORT}:${PORT}"

    environment:
      NODE_ENV: development
      PORT: ${PORT}

      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.4 # 26.7.0 is not a valid version --> https://hub.docker.com/_/mysql/tags?name=8.4&utm_source=chatgpt.com
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s

  redis:
    image: redis:8.10.2

    volumes:
      - redis-data:/data

    healthcheck:
      test:
        ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  node_modules:
  mysql_data:
  redis-data: